server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/diploma
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        default_schema: cloudstorage_diploma
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    default_schema: cloudstorage_diploma
    change-log: classpath:db/changelog/db.changelog-master.yaml

#  main:
#    allow-circular-references: true

app:
  jwt:
    secret: "54gQHhubH0sL4YubnGpjHxbU1caubwcuvgHk9XpuOEk="
    expiration: 60m

  configuration:
    cors:
      origins: 'http://localhost:8080'
      methods: '*'
      headers: '*'
      allow-credentials: true
    threadPoolTaskExecutor:
      corePoolSize: 50
      maxPoolSize: 50






