server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/cloudstorage_diploma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 805E635266556A586E3272357538782F413F4428472B4B6250645367566B5805
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

configuration:
    cors:
      origins: 'http://localhost:8091'
      methods: '*'
      headers: '*'
      allow-credentials: true
    threadPoolTaskExecutor:
      corePoolSize: 50
      maxPoolSize: 50
